### ISSUE TITLE
Visualization: + and - branches are shifted

### ISSUE THREAD

**Issue by tshemsedinov** [b-os-tech/Demo#19]
Both branches `+` and `-` are shifted to the previous block, see and compare

![Screenshot from 2022-05-01 23-19-14](https://user-images.githubusercontent.com/4405297/166163164-90ad1cf7-1753-4e15-af98-78a7d6b8725d.png)

**Comment by leonpolak** [comment]
Fixed in the next pull request

**Comment by leonpolak** [comment]
It's not shifted anymore
